package remediation

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rolloutguardian/rolloutguardian/internal/aggregator"
	"github.com/rolloutguardian/rolloutguardian/internal/config"
	"github.com/rolloutguardian/rolloutguardian/internal/harnessclient"
	"github.com/rolloutguardian/rolloutguardian/internal/policy"
	"gopkg.in/yaml.v3"
)

func TestGenerateManifest_BlockDecision(t *testing.T) {
	tmpDir := t.TempDir()
	cfg := &config.RemediationConfig{
		AutoGenerate: true,
		OutputDir:    tmpDir,
	}

	gen := NewGenerator(cfg)
	decision := &policy.DecisionResult{
		Decision: "block",
		FlagKey:  "checkout-v2-express-pay",
		Reasons:  []string{"payment-service has no chaos coverage within 90 days"},
		BlastRadius: []aggregator.AggregatedServiceSignal{
			{Service: "payment-service", Confidence: 0.94},
		},
	}

	catalog := []harnessclient.CatalogService{
		{
			Name: "payment-service",
			K8sTarget: &harnessclient.K8sTargetInfo{
				Namespace:     "payments",
				LabelSelector: "app=payment-service",
				ClusterID:     "prod-payments-cluster",
			},
		},
	}

	path, err := gen.GenerateManifest(context.Background(), decision, catalog)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if path == "" {
		t.Fatal("expected non-empty manifest path, got empty")
	}

	// Verify file exists
	if _, err := os.Stat(filepath.Join(tmpDir, "payment-service-pod-delete-min.yaml")); os.IsNotExist(err) {
		t.Fatal("expected generated manifest file to exist on disk")
	}

	// Verify YAML content
	data, err := os.ReadFile(filepath.Join(tmpDir, "payment-service-pod-delete-min.yaml"))
	if err != nil {
		t.Fatalf("failed reading generated manifest: %v", err)
	}

	var manifest ExperimentManifest
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("failed parsing generated YAML: %v", err)
	}

	if manifest.Experiment.Name != "payment-service-pod-delete-min" {
		t.Errorf("expected experiment name payment-service-pod-delete-min, got %s", manifest.Experiment.Name)
	}
	if manifest.Experiment.GeneratedBy != "rolloutguardian" {
		t.Errorf("expected generated_by rolloutguardian, got %s", manifest.Experiment.GeneratedBy)
	}
	if manifest.Experiment.GeneratedForFlag != "checkout-v2-express-pay" {
		t.Errorf("expected generated_for_flag checkout-v2-express-pay, got %s", manifest.Experiment.GeneratedForFlag)
	}
	if manifest.Experiment.Target.Namespace != "payments" {
		t.Errorf("expected namespace payments, got %s", manifest.Experiment.Target.Namespace)
	}
	if len(manifest.Experiment.Faults) == 0 {
		t.Fatal("expected at least one fault definition")
	}
	if manifest.Experiment.Faults[0].Name != "pod-delete" {
		t.Errorf("expected fault type pod-delete, got %s", manifest.Experiment.Faults[0].Name)
	}
}

func TestGenerateManifest_AllowDecision_NoOutput(t *testing.T) {
	cfg := &config.RemediationConfig{
		AutoGenerate: true,
		OutputDir:    t.TempDir(),
	}

	gen := NewGenerator(cfg)
	decision := &policy.DecisionResult{
		Decision: "allow",
		FlagKey:  "test-flag",
	}

	path, err := gen.GenerateManifest(context.Background(), decision, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if path != "" {
		t.Errorf("expected empty path for allow decision, got %s", path)
	}
}

func TestGenerateManifest_AutoGenerateDisabled(t *testing.T) {
	cfg := &config.RemediationConfig{
		AutoGenerate: false,
		OutputDir:    t.TempDir(),
	}

	gen := NewGenerator(cfg)
	decision := &policy.DecisionResult{
		Decision: "block",
		FlagKey:  "test-flag",
		Reasons:  []string{"some-service stale"},
	}

	path, err := gen.GenerateManifest(context.Background(), decision, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if path != "" {
		t.Errorf("expected empty path when auto_generate=false, got %s", path)
	}
}

func TestGenerateManifest_K8sTargetFallback(t *testing.T) {
	tmpDir := t.TempDir()
	cfg := &config.RemediationConfig{
		AutoGenerate: true,
		OutputDir:    tmpDir,
	}

	gen := NewGenerator(cfg)
	decision := &policy.DecisionResult{
		Decision: "block",
		FlagKey:  "test-flag",
		Reasons:  []string{"some-service stale chaos"},
		BlastRadius: []aggregator.AggregatedServiceSignal{
			{Service: "some-service", Confidence: 0.75},
		},
	}

	// Empty catalog — should use auto-generated K8s target info
	path, err := gen.GenerateManifest(context.Background(), decision, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if path == "" {
		t.Fatal("expected non-empty path")
	}

	data, _ := os.ReadFile(filepath.Join(tmpDir, "some-service-pod-delete-min.yaml"))
	var manifest ExperimentManifest
	_ = yaml.Unmarshal(data, &manifest)

	// Fallback should auto-derive namespace from service name
	if !strings.Contains(manifest.Experiment.Target.LabelSelector, "some-service") {
		t.Errorf("expected auto-derived label selector containing some-service, got %s", manifest.Experiment.Target.LabelSelector)
	}
}

func TestGenerateManifest_SetsRemediationOnDecision(t *testing.T) {
	tmpDir := t.TempDir()
	cfg := &config.RemediationConfig{
		AutoGenerate: true,
		OutputDir:    tmpDir,
	}

	gen := NewGenerator(cfg)
	decision := &policy.DecisionResult{
		Decision: "block",
		FlagKey:  "test-flag",
		Reasons:  []string{"target-service stale"},
		BlastRadius: []aggregator.AggregatedServiceSignal{
			{Service: "target-service", Confidence: 0.9},
		},
	}

	_, _ = gen.GenerateManifest(context.Background(), decision, nil)

	if decision.SuggestedRemediation == "" {
		t.Error("expected SuggestedRemediation to be set on the decision result after generation")
	}
}
